Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_check_update = false
  config.vm.define "project6"

   config.vm.provider "virtualbox" do |vb|
     vb.gui = false
     vb.memory = "2048"
   end

config.vm.provision "shell", path: "script.sh"
config.vm.provision "file", source: "./empty_file.txt", destination: "/home/vagrant/empty_file.txt"

end
